FROM node:22-alpine

# Установка рабочей директории
WORKDIR /frontend

# Копирование package.json и package-lock.json
COPY /frontend/package*.json ./

# Установка зависимостей
RUN npm install pnpm
RUN npm install

# Копирование исходного кода
COPY /frontend .

# Установка переменных окружения для React
ENV CHOKIDAR_USEPOLLING=true

# Команда запуска разработческого сервера
CMD ["pnpm", "run", "dev"]